<#
    .SYNOPSIS
    This script configures production alerts for Repository Validator

    .DESCRIPTION
    This retrieves correct function app endpoint which receives the alerts
    generated by repository validator.

    .PARAMETER MonitoredWebAppResourceGroup
    This should be the resource group which contains repository validator

    .PARAMETER MonitoredWebAppName
    This should be the name of the repository validator web app

    .PARAMETER AlertHandlingResourceGroup
    This is there resource group where the alert receiver is
    
    .PARAMETER AlertHandlingWebAppName
    Name of the web app which handles the alerts

    .PARAMETER AlertHandlingFunction
    Name of the function which handles the alert. This is used to fetch
    the correct url and code for the web hook

    .PARAMETER AlertSlackChannel
    Slack channel which receives the alerts. This is used as part of the
    web hook url
#>
param(
    [Parameter(Mandatory)][string]$MonitoredWebAppResourceGroup,
    [Parameter(Mandatory)][string]$MonitoredWebAppName,
    [Parameter(Mandatory)][string]$AlertHandlingResourceGroup,
    [Parameter()][string]$AlertHandlingWebAppName = $AlertHandlingResourceGroup,
    [Parameter()][string]$AlertHandlingFunction = 'AlertEndpoint',
    [Parameter(Mandatory)][string]$AlertSlackChannel
)
$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$webApp = Get-AzWebApp `
    -ResourceGroupName $AlertHandlingResourceGroup `
    -Name $AlertHandlingWebAppName

$addressTemplate = .\Deployment\Get-FunctionUri.ps1  `
    -WebApp $webApp `
    -FunctionName $AlertHandlingFunction

$address = $addressTemplate -Replace '{channel}', $AlertSlackChannel

.\Deployment\Set-ActionGroup.ps1 `
    -AlertUrl $address `
    -ActionGroupResourceGroup $MonitoredWebAppResourceGroup `
    -ActionGroupName 'repo-alerts'

.\Deployment\Add-Alerts.ps1 `
    -ResourceGroup $MonitoredWebAppResourceGroupe `
    -AlertTargetResourceGroup $MonitoredWebAppResourceGroup `
    -AlertTargetGroupName 'repo-alerts'